import React from "react";

const GlobalContext = React.createContext({
  currentFile: "",
  currentClip: 0,
  numApiRequests: 0,
  totalFiles: 0,
  totalClipsInFile: 0,
  step: -1,
  timePerClip: 0,
  processStarted: false,
  filesToProcess: [],
  speechLanguage: "ar",
  apiKey: "",
  interfaceLanguage: "ar",
  outputDirectory: "",
  currentSubtitle: "",
  loading: false,
  conversionEngine: "wit",
  error: "",
  theme: "light",
  setSpeechLanguage: () => {},
  setApiKey: () => {},
  setInterfaceLanguage: () => {},
  setOutputDirectory: () => {},
  setConversionEngine: () => {},
  setProcessStarted: () => {},
  setCurrentFile: () => {},
  setCurrentSubtitle: () => {},
  setLoading: () => {},
  setTheme: () => {},
  setCurrentClip: () => {},
  setNumApiRequests: () => {},
  setTotalFiles: () => {},
  setTotalClipsInFile: () => {},
  setFilesToProcess: () => {},
  setStep: () => {},
  setTimePerClip: () => {},
  resetStats: () => {},
  setError: () => {},
});

export default GlobalContext;
