import LocalizedStrings from "react-localization";

const loc = new LocalizedStrings({
  en: {
    app_name: "Sada",
    tagline: "Turn voice into text",
    theme: "Theme",
    dark: "dark",
    light: "light",
    pleaseEnterApiKey: "Please enter your Wit.ai token",
    pleaseAddSomeFiles: "Please add some files",
    open_out_dir: "Open folder",
    speech_language: "Speech language",
    arabic: "Arabic",
    english: "English",
    conversion_engine: "Engine",
    interface_language: "Interface language",
    choose_output_directory: "Choose output folder",
    enter_wit_api_key: "Wit.ai token",
    save: "Save",
    add: "Add",
    clear: "Clear",
    drag_and_drop_or_click_select_button: "Drag & drop files, or click Add",
    drop_files_here: "Drop files here",
    start: "Start",
    stop: "Stop",
    files: "Files",
    estimated_time: "Estimated time",
    hour: "Hr",
    min: "Min",
    network: "Network",
    requests: "Requests",
    split_audio_files: "Split audio",
    upload_to_server: "Transcribe",
    version_label: "Version",
    project_updates: "Project & updates",
    how_to_get_token: "How to get a free token",
    free_note: "Wit.ai is free from Meta — the token is yours and stays on your device.",
    token_help_title: "Get your free Wit.ai token",
    token_step1: "Open wit.ai and sign in with a free Meta account.",
    token_step2: "Create a new App and set its language to Arabic.",
    token_step3: "Open the app's Settings (gear icon).",
    token_step4: "Copy the Server Access Token (not the Client token).",
    token_step5: "Paste it below. It is stored only on this device.",
    open_wit: "Open wit.ai",
    close: "Close",
  },
  ar: {
    app_name: "صدى",
    tagline: "حوّل الصوت إلى نص",
    theme: "السمة",
    dark: "داكن",
    light: "فاتح",
    pleaseEnterApiKey: "الرجاء إدخال مفتاح wit.ai",
    pleaseAddSomeFiles: "أضف بعض الملفات",
    open_out_dir: "مجلد الإخراج",
    speech_language: "لغة التحويل",
    arabic: "عربي",
    english: "إنكليزي",
    conversion_engine: "محرك التحويل",
    interface_language: "لغة الواجهة",
    choose_output_directory: "اختر مجلد الإخراج",
    enter_wit_api_key: "مفتاح wit.ai",
    save: "حفظ",
    add: "إضافة",
    clear: "مسح",
    drag_and_drop_or_click_select_button: "اسحب وأفلت الملفات، أو اضغط إضافة",
    drop_files_here: "أفلت الملفات هنا",
    start: "ابدأ",
    stop: "إيقاف",
    files: "الملفات",
    estimated_time: "الوقت المقدر",
    hour: "ساعة",
    min: "دقيقة",
    network: "الشبكة",
    requests: "الطلبات",
    split_audio_files: "تقسيم الصوت",
    upload_to_server: "التفريغ",
    version_label: "الإصدار",
    project_updates: "المشروع والتحديثات",
    how_to_get_token: "كيف تحصل على مفتاح مجاني",
    free_note: "خدمة wit.ai مجانية من Meta — المفتاح ملكك ويبقى على جهازك.",
    token_help_title: "احصل على مفتاح wit.ai المجاني",
    token_step1: "افتح موقع wit.ai وسجّل الدخول بحساب Meta مجاني.",
    token_step2: "أنشئ تطبيقاً جديداً واضبط لغته على العربية.",
    token_step3: "افتح إعدادات التطبيق (أيقونة الترس).",
    token_step4: "انسخ مفتاح الوصول للخادم (Server Access Token) وليس مفتاح العميل.",
    token_step5: "الصقه بالأسفل. يُحفظ على هذا الجهاز فقط.",
    open_wit: "افتح wit.ai",
    close: "إغلاق",
  },
});

loc.setLanguage("ar");
export default loc;
